### ISSUE TITLE
ImportError: cannot import name 'docevents' from 'botocore.docs.bcdoc'

### ISSUE THREAD

**Issue by maceto** [falnyr/aws-sam-deploy-action#1]
Hi,

Today I started getting this error on actions execution 

```
Run falnyr/aws-sam-deploy-action@v1.1.0
/usr/bin/docker run --name --label --workdir /github/workspace --rm -e TEMPLATE -e AWS_STACK_NAME -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEPLOY_BUCKET -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/xxxx-xxx/xxxx-xxxx":"/github/workspace" 
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.8/site-packages/awscli/clidriver.py", line 36, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/lib/python3.8/site-packages/awscli/help.py", line 23, in <module>
    from botocore.docs.bcdoc import docevents
ImportError: cannot import name 'docevents' from 'botocore.docs.bcdoc' (/usr/lib/python3.8/site-packages/botocore/docs/bcdoc/__init__.py)
```

Reading I found the solution is upgrading aws-cli

```
Upgrading awscli to >=1.18.140 should fix this: [aws/aws-cli#5538](https://github.com/aws/aws-cli/pull/5538)
```

In your Dockerfile when install aws-cli is a older version. I'm not sure how install the latest version of aws-cli on Alpine.

Thank you

**Comment by falnyr** [comment]
hi @maceto, thanks for raising the issue!

I added an update replacing AWS CLI with version 2. If you update to `falnyr/aws-sam-deploy-action@v1.2.1` you should be all good.

**Comment by maceto** [comment]
@falnyr Thanks to you for the fix so fast and keep maintaining the tool!
